### ISSUE TITLE
Very Minor Documentation issue?

### ISSUE THREAD

**Issue by jacoby** [sdondley/Log-Log4perl-Shortcuts#1]
Docs say:

> Instead of this:
>> `$log->info('I am doing something.');`

> You can save some keystrokes and do this:
>> `logw('I am doing something.', 'my.category');`

Shouldn't either the first example be `$log->warn()` or the second be `logi()`?

**Comment by sdondley** [comment]
Uh, yup. Thanks for taking the time to report. I will take care of it.

**Comment by sdondley** [comment]
Fixed with latest release.
