### ISSUE TITLE
Undeclared dependencies

### ISSUE THREAD

**Issue by eserte** [sdondley/Log-Log4perl-Shortcuts#2]
The test suite of Log-Log4perl-Shortcuts-0.019 fails if Module::Data or an too old version of Path::Tiny (<0.108) are installed. Probably the prereqs should be adjusted.

**Comment by eserte** [comment]
Also undeclared: Log::Log4perl

**Comment by eserte** [comment]
And: Test::Output, Test::NoWarnings, Test::Warn

**Comment by sdondley** [comment]
Thanks for the report. Yeah, I'm new to this cpan dependency stuff. I've been trying different settings. Working on it.

**Comment by sdondley** [comment]
Just posted 0.021. We'll see if that fixes everything. Probably not. :)

**Comment by eserte** [comment]
Right now it looks good, everything's green: http://fast-matrix.cpantesters.org/?dist=Log-Log4perl-Shortcuts%200.021

**Comment by sdondley** [comment]
The real test will be to see if it installs on Windows. My module required log4perl 1.47 because 1.48 and 1.49 fail to install on windows. But I think the testers have force installed 1.49. I'm hoping they will downgrade to 1.47, but probably not.

**Comment by eserte** [comment]
Downgrading just by using prereq versions is not possible when using CPAN.pm (with good reasons).

But I started my seldomly used Windows smoker and installed Log-Log4perl-1.47 manually. Your module passes all tests on this system: http://www.cpantesters.org/cpan/report/eed7765c-b922-11e8-b46d-bf8bc25bb5d9

**Comment by sdondley** [comment]
OK, sweet. Thanks. Yeah, it installed on my virtual copy of Windows, too. I'm really just trying to make it as easy as possible for users to install my Anki::Import module which relies on Log::Log4perl::Shortcuts which I use to provide --verbose output for the module. That and I'm just trying to learn about module dependencies/dist zilla, etc. I obviously have a lot to learn.
