### ISSUE TITLE
== instead of eq used in t/03-set_log_config.t

### ISSUE THREAD

**Issue by eserte** [sdondley/Log-Log4perl-Shortcuts#4]
See http://www.cpantesters.org/cpan/report/102054923 for a fail report. It seems that the test script is using `==` instead of `eq` in line 29, thus generating warnings on some systems (maybe depending on Test::More version or so).

And actually it's better to use `is` instead of `ok` here, because diagnostics is better in case of real failures.

**Comment by sdondley** [comment]
Thanks! New release has fixed it.
